sudo: false
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'pypy'
  - 'pypy'
  - 'pypy-0.7.0'

install:
    - pip install -e .
    - pip install -r requirements.txt
script: 
    - python tests/example.py

after_success: 
    - codecov
    - coverage combine

notifications:
  email: true
