sudo: false
language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - 'pypy-5.3.1'
  - 'pypy3.5-5.7.1-beta'
  
matrix:
  allow_failures:
    - python: 'pypy3.5-5.7.1-beta'
    
install:
    - pip install -e
    - pip install codecov
script: make test

after_success: 
    - codecov
    - coverage combine

notifications:
  email: true
