site_name: saucpy (Semiparametric AUC in Python)

pages:
    - Home: index.md
    - Installation: install.md
    - Article: paper.md
    - Example: example-python.html
    - saucpy Methods: python-methods.md
    - SemiparametricAUC.jl in Julia: example-julia.html  
    - sAUC in R: example.html  
    - sAUC in R Shiny: r-shiny.md
    - Developer: bohora.md
    - Report Bugs: bug-report.md

theme: readthedocs
    
markdown_extensions:
  - mdx_math
  - smarty